mutation RestoreOldSkuInventoryBatch6 {
  m1: inventoryAdjustQuantities(input: {
    reason: "correction",
    name: "available",
    changes: [{
      inventoryItemId: "gid://shopify/InventoryItem/55716630266166",
      locationId: "gid://shopify/Location/107681382710",
      delta: 3
    }]
  }) {
    inventoryAdjustmentGroup { id }
    userErrors { field message code }
  }
  m2: inventoryAdjustQuantities(input: {
    reason: "correction",
    name: "available",
    changes: [{
      inventoryItemId: "gid://shopify/InventoryItem/55716630266166",
      locationId: "gid://shopify/Location/60899721289",
      delta: 3
    }]
  }) {
    inventoryAdjustmentGroup { id }
    userErrors { field message code }
  }
  m3: inventoryAdjustQuantities(input: {
    reason: "correction",
    name: "available",
    changes: [{
      inventoryItemId: "gid://shopify/InventoryItem/55716630266166",
      locationId: "gid://shopify/Location/107681972534",
      delta: 3
    }]
  }) {
    inventoryAdjustmentGroup { id }
    userErrors { field message code }
  }
  m4: inventoryAdjustQuantities(input: {
    reason: "correction",
    name: "available",
    changes: [{
      inventoryItemId: "gid://shopify/InventoryItem/55716630298934",
      locationId: "gid://shopify/Location/110138032438",
      delta: 10
    }]
  }) {
    inventoryAdjustmentGroup { id }
    userErrors { field message code }
  }
  m5: inventoryAdjustQuantities(input: {
    reason: "correction",
    name: "available",
    changes: [{
      inventoryItemId: "gid://shopify/InventoryItem/55716630298934",
      locationId: "gid://shopify/Location/107681349942",
      delta: 3
    }]
  }) {
    inventoryAdjustmentGroup { id }
    userErrors { field message code }
  }
  m6: inventoryAdjustQuantities(input: {
    reason: "correction",
    name: "available",
    changes: [{
      inventoryItemId: "gid://shopify/InventoryItem/55716630298934",
      locationId: "gid://shopify/Location/107681874230",
      delta: 3
    }]
  }) {
    inventoryAdjustmentGroup { id }
    userErrors { field message code }
  }
  m7: inventoryAdjustQuantities(input: {
    reason: "correction",
    name: "available",
    changes: [{
      inventoryItemId: "gid://shopify/InventoryItem/55716630298934",
      locationId: "gid://shopify/Location/107682201910",
      delta: 3
    }]
  }) {
    inventoryAdjustmentGroup { id }
    userErrors { field message code }
  }
  m8: inventoryAdjustQuantities(input: {
    reason: "correction",
    name: "available",
    changes: [{
      inventoryItemId: "gid://shopify/InventoryItem/55716721361206",
      locationId: "gid://shopify/Location/60899721289",
      delta: 10
    }]
  }) {
    inventoryAdjustmentGroup { id }
    userErrors { field message code }
  }
  m9: inventoryAdjustQuantities(input: {
    reason: "correction",
    name: "available",
    changes: [{
      inventoryItemId: "gid://shopify/InventoryItem/55716721393974",
      locationId: "gid://shopify/Location/107681939766",
      delta: 10
    }]
  }) {
    inventoryAdjustmentGroup { id }
    userErrors { field message code }
  }
  m10: inventoryAdjustQuantities(input: {
    reason: "correction",
    name: "available",
    changes: [{
      inventoryItemId: "gid://shopify/InventoryItem/55716721393974",
      locationId: "gid://shopify/Location/107681972534",
      delta: 10
    }]
  }) {
    inventoryAdjustmentGroup { id }
    userErrors { field message code }
  }
  m11: inventoryAdjustQuantities(input: {
    reason: "correction",
    name: "available",
    changes: [{
      inventoryItemId: "gid://shopify/InventoryItem/55716721426742",
      locationId: "gid://shopify/Location/107681841462",
      delta: 10
    }]
  }) {
    inventoryAdjustmentGroup { id }
    userErrors { field message code }
  }
  m12: inventoryAdjustQuantities(input: {
    reason: "correction",
    name: "available",
    changes: [{
      inventoryItemId: "gid://shopify/InventoryItem/55716721426742",
      locationId: "gid://shopify/Location/107681939766",
      delta: 10
    }]
  }) {
    inventoryAdjustmentGroup { id }
    userErrors { field message code }
  }
  m13: inventoryAdjustQuantities(input: {
    reason: "correction",
    name: "available",
    changes: [{
      inventoryItemId: "gid://shopify/InventoryItem/55716721426742",
      locationId: "gid://shopify/Location/60899721289",
      delta: 10
    }]
  }) {
    inventoryAdjustmentGroup { id }
    userErrors { field message code }
  }
  m14: inventoryAdjustQuantities(input: {
    reason: "correction",
    name: "available",
    changes: [{
      inventoryItemId: "gid://shopify/InventoryItem/55716721459510",
      locationId: "gid://shopify/Location/60899721289",
      delta: 10
    }]
  }) {
    inventoryAdjustmentGroup { id }
    userErrors { field message code }
  }
  m15: inventoryAdjustQuantities(input: {
    reason: "correction",
    name: "available",
    changes: [{
      inventoryItemId: "gid://shopify/InventoryItem/55716721525046",
      locationId: "gid://shopify/Location/107681448246",
      delta: 10
    }]
  }) {
    inventoryAdjustmentGroup { id }
    userErrors { field message code }
  }
  m16: inventoryAdjustQuantities(input: {
    reason: "correction",
    name: "available",
    changes: [{
      inventoryItemId: "gid://shopify/InventoryItem/55716721525046",
      locationId: "gid://shopify/Location/107681841462",
      delta: 10
    }]
  }) {
    inventoryAdjustmentGroup { id }
    userErrors { field message code }
  }
  m17: inventoryAdjustQuantities(input: {
    reason: "correction",
    name: "available",
    changes: [{
      inventoryItemId: "gid://shopify/InventoryItem/55716721525046",
      locationId: "gid://shopify/Location/35316531273",
      delta: 10
    }]
  }) {
    inventoryAdjustmentGroup { id }
    userErrors { field message code }
  }
  m18: inventoryAdjustQuantities(input: {
    reason: "correction",
    name: "available",
    changes: [{
      inventoryItemId: "gid://shopify/InventoryItem/55716721525046",
      locationId: "gid://shopify/Location/107681874230",
      delta: 10
    }]
  }) {
    inventoryAdjustmentGroup { id }
    userErrors { field message code }
  }
  m19: inventoryAdjustQuantities(input: {
    reason: "correction",
    name: "available",
    changes: [{
      inventoryItemId: "gid://shopify/InventoryItem/55716721525046",
      locationId: "gid://shopify/Location/107681939766",
      delta: 10
    }]
  }) {
    inventoryAdjustmentGroup { id }
    userErrors { field message code }
  }
  m20: inventoryAdjustQuantities(input: {
    reason: "correction",
    name: "available",
    changes: [{
      inventoryItemId: "gid://shopify/InventoryItem/55716721525046",
      locationId: "gid://shopify/Location/60899721289",
      delta: 10
    }]
  }) {
    inventoryAdjustmentGroup { id }
    userErrors { field message code }
  }
  m21: inventoryAdjustQuantities(input: {
    reason: "correction",
    name: "available",
    changes: [{
      inventoryItemId: "gid://shopify/InventoryItem/55716721525046",
      locationId: "gid://shopify/Location/107681972534",
      delta: 10
    }]
  }) {
    inventoryAdjustmentGroup { id }
    userErrors { field message code }
  }
  m22: inventoryAdjustQuantities(input: {
    reason: "correction",
    name: "available",
    changes: [{
      inventoryItemId: "gid://shopify/InventoryItem/55716721525046",
      locationId: "gid://shopify/Location/107682201910",
      delta: 10
    }]
  }) {
    inventoryAdjustmentGroup { id }
    userErrors { field message code }
  }
  m23: inventoryAdjustQuantities(input: {
    reason: "correction",
    name: "available",
    changes: [{
      inventoryItemId: "gid://shopify/InventoryItem/55716721590582",
      locationId: "gid://shopify/Location/107681874230",
      delta: 10
    }]
  }) {
    inventoryAdjustmentGroup { id }
    userErrors { field message code }
  }
  m24: inventoryAdjustQuantities(input: {
    reason: "correction",
    name: "available",
    changes: [{
      inventoryItemId: "gid://shopify/InventoryItem/55716721656118",
      locationId: "gid://shopify/Location/20829700169",
      delta: 10
    }]
  }) {
    inventoryAdjustmentGroup { id }
    userErrors { field message code }
  }
  m25: inventoryAdjustQuantities(input: {
    reason: "correction",
    name: "available",
    changes: [{
      inventoryItemId: "gid://shopify/InventoryItem/55716721688886",
      locationId: "gid://shopify/Location/35316531273",
      delta: 10
    }]
  }) {
    inventoryAdjustmentGroup { id }
    userErrors { field message code }
  }
  m26: inventoryAdjustQuantities(input: {
    reason: "correction",
    name: "available",
    changes: [{
      inventoryItemId: "gid://shopify/InventoryItem/55716721688886",
      locationId: "gid://shopify/Location/107681939766",
      delta: 10
    }]
  }) {
    inventoryAdjustmentGroup { id }
    userErrors { field message code }
  }
  m27: inventoryAdjustQuantities(input: {
    reason: "correction",
    name: "available",
    changes: [{
      inventoryItemId: "gid://shopify/InventoryItem/55716721688886",
      locationId: "gid://shopify/Location/60899721289",
      delta: 10
    }]
  }) {
    inventoryAdjustmentGroup { id }
    userErrors { field message code }
  }
  m28: inventoryAdjustQuantities(input: {
    reason: "correction",
    name: "available",
    changes: [{
      inventoryItemId: "gid://shopify/InventoryItem/55716721688886",
      locationId: "gid://shopify/Location/35316498505",
      delta: 10
    }]
  }) {
    inventoryAdjustmentGroup { id }
    userErrors { field message code }
  }
  m29: inventoryAdjustQuantities(input: {
    reason: "correction",
    name: "available",
    changes: [{
      inventoryItemId: "gid://shopify/InventoryItem/55716721688886",
      locationId: "gid://shopify/Location/107682201910",
      delta: 10
    }]
  }) {
    inventoryAdjustmentGroup { id }
    userErrors { field message code }
  }
  m30: inventoryAdjustQuantities(input: {
    reason: "correction",
    name: "available",
    changes: [{
      inventoryItemId: "gid://shopify/InventoryItem/55716721721654",
      locationId: "gid://shopify/Location/35316531273",
      delta: 10
    }]
  }) {
    inventoryAdjustmentGroup { id }
    userErrors { field message code }
  }
  m31: inventoryAdjustQuantities(input: {
    reason: "correction",
    name: "available",
    changes: [{
      inventoryItemId: "gid://shopify/InventoryItem/55716721721654",
      locationId: "gid://shopify/Location/107681874230",
      delta: 10
    }]
  }) {
    inventoryAdjustmentGroup { id }
    userErrors { field message code }
  }
  m32: inventoryAdjustQuantities(input: {
    reason: "correction",
    name: "available",
    changes: [{
      inventoryItemId: "gid://shopify/InventoryItem/55716723949878",
      locationId: "gid://shopify/Location/107681874230",
      delta: 10
    }]
  }) {
    inventoryAdjustmentGroup { id }
    userErrors { field message code }
  }
  m33: inventoryAdjustQuantities(input: {
    reason: "correction",
    name: "available",
    changes: [{
      inventoryItemId: "gid://shopify/InventoryItem/55716723949878",
      locationId: "gid://shopify/Location/107682201910",
      delta: 10
    }]
  }) {
    inventoryAdjustmentGroup { id }
    userErrors { field message code }
  }
  m34: inventoryAdjustQuantities(input: {
    reason: "correction",
    name: "available",
    changes: [{
      inventoryItemId: "gid://shopify/InventoryItem/55716723982646",
      locationId: "gid://shopify/Location/35316531273",
      delta: 10
    }]
  }) {
    inventoryAdjustmentGroup { id }
    userErrors { field message code }
  }
  m35: inventoryAdjustQuantities(input: {
    reason: "correction",
    name: "available",
    changes: [{
      inventoryItemId: "gid://shopify/InventoryItem/55716723982646",
      locationId: "gid://shopify/Location/60899721289",
      delta: 10
    }]
  }) {
    inventoryAdjustmentGroup { id }
    userErrors { field message code }
  }
}