# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5a8b9ed20cfb65d0e88463bf3975ee50"
application_url = "https://hera-inventory.onrender.com"
embedded = true
name = "Hera Hub"

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_all_orders,read_customers,write_customers,read_discounts,read_files,write_files,write_inventory,read_inventory,write_inventory_shipments,read_inventory_shipments,write_inventory_transfers,read_inventory_transfers,read_locations,read_orders,read_products,write_products,read_publications,write_publications,read_store_credit_account_transactions,write_store_credit_account_transactions,read_store_credit_accounts,read_translations,write_inventory_shipments_received_items,read_inventory_shipments_received_items"
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://hera-inventory.onrender.com/auth/callback" ]
